# Site settings
title: Crazy [b]log
email: alextalker [at] openmailbox [dot] org
description: > # this means to ignore newlines until "baseurl:"
  Alex Talker personal trash site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alextalker.github.io" # the base hostname & protocol for your site
twitter_username: Alex_Talker
github_username:  AlexTalker

# Build settings
markdown: kramdown
